import test from 'node:test';import assert from 'node:assert/strict';
import {createHouse,mutate,visible,balance,identity,digest} from '../lib/model.js';
import {makeHandler} from '../api/household.js';
const setup=()=>createHouse({name:'Our home',names:['Sagar','Sushma','Nabin','Sujata'],seat:0});
const exp=(h,patch={})=>({merchant:'Groceries',cents:10001,category:'Groceries',payer:0,visibility:'shared',split:'half',date:'2026-09-13',sheet:h.sheets[0].id,notes:'',...patch});
test('equal splits conserve every cent, including odd totals',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});assert.deepEqual(balance(h.expenses),{net:5001,aPaid:10001,bPaid:0,amount:5001});mutate(h,2,{action:'expense',expense:exp(h,{payer:2})});assert.equal(balance(h.expenses).net,1);});
test('full allocations and own-couple expenses balance correctly',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h,{split:'b'})});assert.equal(balance(h.expenses).net,10001);mutate(h,2,{action:'expense',expense:exp(h,{payer:2,split:'a'})});assert.equal(balance(h.expenses).net,0);});
test('private records are absent from other couple responses and settlement',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h,{visibility:'private'})});assert.equal(visible(h,2).expenses.length,0);assert.equal(visible(h,1).expenses.length,1);assert.equal(balance(h.expenses).amount,0);assert.equal(visible(h,0).keys,undefined);});
test('cannot create private expenses for the other couple',()=>{const{h}=setup();assert.throws(()=>mutate(h,0,{action:'expense',expense:exp(h,{payer:2,visibility:'private'})}),/your couple/);});
test('hidden private record cannot be changed by former shared author',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h,{payer:2})});const e=h.expenses[0];mutate(h,2,{action:'expense',expense:{...e,visibility:'private'}});assert.throws(()=>mutate(h,0,{action:'delete',id:e.id}),/cannot be deleted/);assert.throws(()=>mutate(h,0,{action:'expense',expense:{...e,cents:1}}),/Only its author/);});
test('settlement locks shared entries, leaves private entries untouched',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});mutate(h,0,{action:'expense',expense:exp(h,{visibility:'private'})});mutate(h,0,{action:'settle',sheet:h.sheets[0].id});const e=h.expenses.find(e=>e.visibility==='shared');assert.ok(e.settlement);assert.equal(h.expenses[0].settlement,null);assert.equal(balance(h.expenses).net,0);assert.throws(()=>mutate(h,0,{action:'delete',id:e.id}));assert.throws(()=>mutate(h,0,{action:'expense',expense:e}));});
test('rejects invalid money and receipt payloads',()=>{for(const cents of [0,-1,1.1,NaN,1000000000]){const{h}=setup();assert.throws(()=>mutate(h,0,{action:'expense',expense:exp(h,{cents})}));}const{h}=setup();assert.throws(()=>mutate(h,0,{action:'expense',expense:exp(h,{receipt:'data:image/svg+xml,<script>'})}));});
test('only author or payer may edit shared records',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});assert.throws(()=>mutate(h,1,{action:'delete',id:h.expenses[0].id}));});
test('archiving requires shared settlement and prevents new entries',()=>{const{h}=setup();mutate(h,0,{action:'expense',expense:exp(h)});assert.throws(()=>mutate(h,0,{action:'archive',id:h.sheets[0].id}));mutate(h,0,{action:'settle',sheet:h.sheets[0].id});mutate(h,0,{action:'archive',id:h.sheets[0].id});assert.throws(()=>mutate(h,0,{action:'expense',expense:exp(h)}));});
test('private access key is stored as a hash and checked',()=>{const{h,key}=setup();assert.equal(identity(h,key),0);assert.equal(h.keys[0],digest(key));assert.notEqual(h.keys[0],key);assert.throws(()=>identity(h,'wrong'));});
function fakeDb(){const m=new Map();return async(cmd,...a)=>{if(cmd==='GET')return m.get(a[0])??null;if(cmd==='SET'){if(a[2]==='NX'&&m.has(a[0]))return null;m.set(a[0],a[1]);return'OK';}if(cmd==='INCR'){const v=(m.get(a[0])||0)+1;m.set(a[0],v);return v;}if(cmd==='EXPIRE')return 1;if(cmd==='EVAL'){const[,key,old,next]=a.slice(1);if(m.get(key)!==old)return 0;m.set(key,next);return 1;}};}
async function request(fn,body,key='',headers={}){let code;let result;const res={setHeader(){},status(c){code=c;return this;},json(j){result=j;return this;}};await fn({method:'POST',headers:{host:'example.com',authorization:'Bearer '+key,...headers},body},res);return{code,...result};}
test('API create, join, read, edit and stale revision rejection',async()=>{const fn=makeHandler(fakeDb());const owner=await request(fn,{action:'create',name:'Home',names:['A','B','C','D'],seat:0});assert.equal(owner.code,200);const house=owner.data.id;const joined=await request(fn,{action:'join',house,invite:owner.data.invite,seat:2});assert.equal(joined.code,200);const now=await request(fn,{action:'read',house},owner.key);assert.equal(now.code,200);const saved=await request(fn,{action:'expense',house,rev:now.data.rev,expense:exp(now.data,{visibility:'private'})},owner.key);assert.equal(saved.code,200);const outsider=await request(fn,{action:'read',house},joined.key);assert.equal(outsider.data.expenses.length,0);const stale=await request(fn,{action:'settings',house,rev:now.data.rev,name:'Changed',names:['A','B','C','D']},owner.key);assert.equal(stale.code,409);const invalid=await request(fn,{action:'read',house},'x'.repeat(64));assert.equal(invalid.code,401);});
test('API rejects cross-origin requests and duplicate seat claims',async()=>{const fn=makeHandler(fakeDb());assert.equal((await request(fn,{action:'create'},'',{origin:'https://evil.example'})).code,403);const owner=await request(fn,{action:'create',name:'Home',names:['A','B','C','D'],seat:0});assert.equal((await request(fn,{action:'join',house:owner.data.id,invite:owner.data.invite,seat:0})).code,409);});
