import {catalogValues,changeCatalog} from '../public/catalog.js';
import {randomBytes,createHash} from 'node:crypto';
export const id=()=>randomBytes(16).toString('hex');
export const digest=s=>createHash('sha256').update(s).digest('hex');
export const group=seat=>seat<2?'a':'b';
export function assert(ok,message,status=400){if(!ok)throw Object.assign(new Error(message),{status});}
export function text(v,max=100){assert(typeof v==='string'&&v.trim().length>0&&v.length<=max,'Please check the text fields.');return v.trim();}
export function date(v){const parsed=new Date(v+'T12:00:00Z');assert(/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(parsed.getTime())&&parsed.toISOString().slice(0,10)===v,'Choose a valid date.');return v;}
export function balance(expenses){let net=0,aPaid=0,bPaid=0;for(const e of expenses){if(e.visibility==='private'||e.settlement)continue;const aShare=e.split==='half'?Math.floor(e.cents/2):e.split==='a'?e.cents:0;if(group(e.payer)==='a'){aPaid+=e.cents;net+=e.cents-aShare;}else{bPaid+=e.cents;net-=aShare;}}return{net,aPaid,bPaid,amount:Math.abs(net)};}
export function createHouse(b){assert(Array.isArray(b.names)&&b.names.length===4,'Enter four household members.');assert(Number.isInteger(b.seat)&&b.seat>=0&&b.seat<4,'Choose your name.');const key=id()+id();const h={id:id(),name:text(b.name),names:b.names.map(n=>text(n,40)),keys:[null,null,null,null],invite:id(),rev:0,expenses:[],sheets:[{id:id(),name:new Date().toLocaleDateString('en-AU',{month:'long',year:'numeric'}),start:new Date().toISOString().slice(0,8)+'01',end:'',archived:false,pinned:true}],settlements:[]};h.keys[b.seat]=digest(key);return{h,key};}
export function identity(h,key){const seat=h.keys.indexOf(digest(key));assert(seat>=0,'Your access key is invalid.',401);return seat;}
export function visible(h,seat){return{id:h.id,name:h.name,names:h.names,claimed:h.keys.map(Boolean),invite:h.invite,rev:h.rev,seat,catalogs:{merchants:catalogValues(h,"merchants"),categories:catalogValues(h,"categories")},expenses:h.expenses.filter(e=>e.visibility==='shared'||group(e.payer)===group(seat)),sheets:h.sheets,settlements:h.settlements};}
export function mutate(h,seat,b){const me=group(seat);let e;switch(b.action){
case 'expense':{e=h.expenses.find(x=>x.id===b.expense.id);assert(!b.expense.id||e,'Expense no longer exists.',404);if(e)assert((e.visibility==='shared'||group(e.payer)===me)&&!e.settlement&&(e.creator===seat||e.payer===seat),'Only its author or payer can change an unsettled expense.',403);const x=b.expense;assert(Number.isInteger(x.cents)&&x.cents>0&&x.cents<=999999999,'Enter an amount from $0.01 to $9,999,999.99.');assert(Number.isInteger(x.payer)&&x.payer>=0&&x.payer<4,'Choose a payer.');assert(['shared','private'].includes(x.visibility)&&['half','a','b'].includes(x.split),'Choose a valid split.');assert(x.visibility!=='private'||group(x.payer)===me,'Private expenses must belong to your couple.',403);assert(h.sheets.some(s=>s.id===x.sheet&&!s.archived),'Choose an open sheet.');assert(!x.receipt||(/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(x.receipt)&&x.receipt.length<400000),'Use a smaller JPEG, PNG or WebP receipt.');const item={id:e?.id||id(),merchant:text(x.merchant,80),cents:x.cents,category:text(x.category,40),payer:x.payer,visibility:x.visibility,split:x.split,date:date(x.date),notes:typeof x.notes==='string'?x.notes.slice(0,500):'',receipt:x.receipt||'',sheet:x.sheet,creator:e?.creator??seat,settlement:null,created:e?.created||new Date().toISOString()};if(e)h.expenses[h.expenses.indexOf(e)]=item;else h.expenses.unshift(item);break;}
case 'delete':e=h.expenses.find(x=>x.id===b.id);assert(e&&(e.visibility==='shared'||group(e.payer)===me)&&!e.settlement&&(e.creator===seat||e.payer===seat),'This expense cannot be deleted.',403);h.expenses=h.expenses.filter(x=>x.id!==b.id);break;
case 'settings':h.name=text(b.name);assert(Array.isArray(b.names)&&b.names.length===4,'Enter all four names.');h.names=b.names.map(n=>text(n,40));break;
case 'sheet':{const s={id:id(),name:text(b.name,60),start:date(b.start),end:b.end?date(b.end):'',pinned:false,archived:false};assert(!s.end||s.end>=s.start,'End date must follow start date.');h.sheets.unshift(s);break;}
case 'archive':{const s=h.sheets.find(s=>s.id===b.id);assert(s,'Sheet not found.');assert(!h.expenses.some(e=>e.sheet===s.id&&e.visibility==='shared'&&!e.settlement),'Settle shared expenses before archiving.');s.archived=!s.archived;break;}
case 'pin':assert(h.sheets.some(s=>s.id===b.id),'Sheet not found.');{const wasPinned=h.sheets.find(s=>s.id===b.id).pinned;for(const s of h.sheets)s.pinned=s.id===b.id&&!wasPinned;}break;
case 'settle':{const items=h.expenses.filter(e=>e.sheet===b.sheet&&e.visibility==='shared'&&!e.settlement);assert(items.length,'No shared expenses to settle.');const total=balance(items);const settlement={id:id(),sheet:b.sheet,net:total.net,date:new Date().toISOString(),by:seat,count:items.length};h.settlements.unshift(settlement);for(const e of items)e.settlement=settlement.id;break;}
case 'catalog':changeCatalog(h,b);break;
case 'sheet-edit':{const s=h.sheets.find(s=>s.id===b.id);assert(s,'Sheet not found.');const name=text(b.name,60),start=date(b.start),end=b.end?date(b.end):'';assert(!end||end>=start,'End date must follow start date.');Object.assign(s,{name,start,end});break;}
case 'sheet-delete':{const s=h.sheets.find(s=>s.id===b.id);assert(s,'Sheet not found.');const items=h.expenses.filter(e=>e.sheet===s.id);assert(!h.settlements.some(r=>r.sheet===s.id)&&items.every(e=>!e.settlement&&(e.visibility==='shared'||group(e.payer)===me)&&(e.creator===seat||e.payer===seat)),'This sheet contains protected records. Archive it instead.',403);h.expenses=h.expenses.filter(e=>e.sheet!==s.id);h.sheets=h.sheets.filter(x=>x.id!==s.id);break;}
case 'rotate-invite':h.invite=id();break;
default:assert(false,'Unknown action.');}
assert(JSON.stringify(h).length<3500000,'Household storage is full. Export your records and contact the app owner.');h.rev++;return h;}
