import {createHouse,identity,visible,mutate,assert,id,digest} from '../lib/model.js';
const CAS="local current=redis.call('GET',KEYS[1]); if current~=ARGV[1] then return 0 end; redis.call('SET',KEYS[1],ARGV[2]); return 1";
async function redis(...cmd){const url=process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_URL;const token=process.env.KV_REST_API_TOKEN||process.env.UPSTASH_REDIS_REST_TOKEN;assert(url&&token,'Shared storage is not connected yet. The app owner needs to finish setup.',503);const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(cmd),signal:AbortSignal.timeout(10000)});assert(r.ok,'Shared storage is temporarily unavailable.',503);const j=await r.json();assert(!j.error,'Shared storage is temporarily unavailable.',503);return j.result;}
export function makeHandler(db=redis){return async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');try{assert(req.method==='POST','Method not allowed.',405);const origin=req.headers.origin;if(origin)assert(new URL(origin).host===req.headers.host,'Request origin is not allowed.',403);const b=typeof req.body==='string'?JSON.parse(req.body):req.body;assert(b&&JSON.stringify(b).length<500000,'Request too large.',413);const ip=digest(String(req.headers['x-forwarded-for']||'local').split(',')[0]);const rateKey=`together:rate:${ip}:${Math.floor(Date.now()/60000)}`;const rate=await db('INCR',rateKey);if(rate===1)await db('EXPIRE',rateKey,120);assert(rate<=120,'Too many requests. Please wait a minute.',429);
if(b.action==='create'){const{h,key}=createHouse(b);await db('SET',`together:house:${h.id}`,JSON.stringify(h),'NX');return res.status(200).json({data:visible(h,b.seat),key});}
assert(typeof b.house==='string'&&/^[a-f0-9]{32}$/.test(b.house),'Enter a valid household link.');const storeKey=`together:house:${b.house}`;const raw=await db('GET',storeKey);assert(raw,'Household not found.',404);const h=JSON.parse(raw);
if(b.action==='join'){assert(typeof b.invite==='string'&&digest(b.invite)===digest(h.invite),'This invitation has expired or is invalid.',403);if(b.seat===undefined)return res.status(200).json({preview:{name:h.name,names:h.names,claimed:h.keys.map(Boolean)}});assert(Number.isInteger(b.seat)&&b.seat>=0&&b.seat<4&&!h.keys[b.seat],'That member already has access. Use their saved access link.',409);const key=id()+id();h.keys[b.seat]=digest(key);h.rev++;assert(await db('EVAL',CAS,1,storeKey,raw,JSON.stringify(h)),'Someone joined at the same time. Try again.',409);return res.status(200).json({data:visible(h,b.seat),key});}
const key=String(req.headers.authorization||'').replace(/^Bearer /,'');assert(key.length===64,'Open your private access link to sign in.',401);const seat=identity(h,key);if(b.action==='read')return res.status(200).json({data:visible(h,seat)});assert(b.rev===h.rev,'New changes arrived. Refresh and try again.',409);mutate(h,seat,b);assert(await db('EVAL',CAS,1,storeKey,raw,JSON.stringify(h)),'New changes arrived. Refresh and try again.',409);res.status(200).json({data:visible(h,seat)});
}catch(err){res.status(err.status||500).json({error:err.status?err.message:'Something went wrong. Please try again.'});}};}
export default makeHandler();
